[package]
name = "abci-rs"
version = "0.1.0"
authors = ["Devashish Dixit <devashish@crypto.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2.8"
integer-encoding = "1.0"
# tokio = { version = "0.2.0-alpha.5", default-features = false, features = ["tcp"] }

[workspace]
members = ["gen-proto"]
