[package]
name = "abci-rs"
version = "0.1.0"
authors = ["Devashish Dixit <devashish@crypto.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
protobuf = "2.8"
integer-encoding = "1.0"

[dev-dependencies]
env_logger = "0.7"

[workspace]
members = ["gen-proto"]
