[package]
name = "abci-rs"
version = "0.3.3"
authors = ["Devashish Dixit <devashishdxt@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A Rust crate for creating ABCI applications"
homepage = "https://github.com/devashishdxt/abci-rs"
documentation = "https://devashishdxt.github.io/abci-rs/abci/"
repository = "https://github.com/devashishdxt/abci-rs"
categories = ["network-programming"]
keywords = ["blockchain", "tendermint", "abci"]
readme = "README.md"
include = ["Cargo.toml", "src/**/*.rs", "README.md"]
edition = "2018"

[lib]
name = "abci"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
protobuf = "2.8"
integer-encoding = "1.0"
async-std = "1.3"
async-trait = "0.1"

[dev-dependencies]
env_logger = "0.7"

[features]
default = []
uds = []

[workspace]
members = ["gen-proto"]
