[package]
name = "abci-rs"
version = "0.6.0"
authors = ["Devashish Dixit <devashishdxt@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A Rust crate for creating ABCI applications"
homepage = "https://github.com/devashishdxt/abci-rs"
repository = "https://github.com/devashishdxt/abci-rs"
categories = ["network-programming"]
keywords = ["blockchain", "tendermint", "abci"]
readme = "README.md"
include = ["Cargo.toml", "src/**/*.rs", "README.md"]
edition = "2018"

[lib]
name = "abci"

[package.metadata.docs.rs]
features = ["doc"]
rustdoc-args = ["--cfg", "feature=\"doc\""]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
protobuf = "2.10"
integer-encoding = "1.0"
async-trait = "0.1"
async-std = { version = "1.4", optional = true }
tokio = { version = "0.2", optional = true, features = ["io-util", "sync", "tcp", "stream", "rt-core", "uds", "fs"] }

[dev-dependencies]
env_logger = "0.7"
tokio = { version = "0.2", features = ["macros"] }

[features]
default = ["tokio"]
doc = []

[workspace]
members = ["gen-proto"]
