[package]
name = "abci-rs"
version = "0.11.0"
authors = ["Devashish Dixit <devashishdxt@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A Rust crate for creating ABCI applications"
homepage = "https://github.com/devashishdxt/abci-rs"
repository = "https://github.com/devashishdxt/abci-rs"
categories = ["network-programming"]
keywords = ["blockchain", "tendermint", "abci"]
readme = "README.md"
include = ["Cargo.toml", "src/**/*.rs", "README.md"]
edition = "2018"

[lib]
name = "abci"

[package.metadata.docs.rs]
features = ["doc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = { version = "1.5", optional = true }
async-std = { version = "1.6", optional = true }
async-trait = "0.1"
integer-encoding = { version = "2.1", optional = true }
prost = "0.6"
prost-types = "0.6"
tendermint-proto = "0.17.0-rc1"
tokio = { version = "1.1", optional = true, features = ["io-util", "sync", "net", "stream", "rt"] }
tracing = { version = "0.1", features = ["log"] }
tracing-futures = "0.2"

[dev-dependencies]
mock-io = { version = "0.2", default-features = false, features = ["async-tokio"] }
tokio = { version = "1.1", features = ["macros", "rt-multi-thread", "time"] }
tracing-subscriber = { version = "0.2", default-features = false, features = ["fmt", "ansi"] }

[features]
default = ["use-tokio"]
doc = []
use-async-std = ["async-channel",  "async-std", "integer-encoding/futures_async"]
use-tokio = ["tokio", "integer-encoding/tokio_async"]
